### ISSUE TITLE
Projucer crashes when setting global-search-path from cmdline

### ISSUE THREAD

**Issue by umlaeute** [WeAreROLI/JUCE#421]
On a fresh installation, where `Projucer` has never been started (and thus no initial configuration has been created), the following crashes:

~~~
Projucer --set-global-search-path linux defaultJuceModulePath /path/to/JUCE/modules
~~~

detailed steps to reproduce:

~~~sh
$ rm -rf ~/.config/Projucer
$ mkdir -p /tmp/JUCE/modules
$ Projucer  --set-global-search-path linux defaultJuceModulePath /tmp/JUCE/modules/
JUCE v5.3.2

**********************************************************
Projucer 5.3.2  ---  Build date: May 14 2018
Log started: 24 Sep 2018 4:53:46pm

Linux
CPU: 1221MHz  Cores: 8  7970MB
Segmentation fault
$
~~~

i would have expected, that Projucer created a new configuration with the requested search-path.

I'm running an amd64 Linux system (Debian/buster).

here's a full backtrace, with a freshly compiled Projucer (todays `develop`, aka dbb1345583adb5ed01c1344f4e34380d481e0a26)

~~~gdb
  (gdb) run
  Thread 1 "Projucer" received signal SIGSEGV, Segmentation fault.
  0x000055555564a9b4 in juce::CharPointer_UTF8::isEmpty (this=0x18)
      at ../../../../modules/juce_core/text/juce_CharPointer_UTF8.h:76
  76          inline bool isEmpty() const noexcept                { return *data == 0; }
  (gdb) bt
  #0  0x000055555564a9b4 in juce::CharPointer_UTF8::isEmpty() const (this=0x18)
      at ../../../../modules/juce_core/text/juce_CharPointer_UTF8.h:76
  #1  0x000055555564a9da in juce::String::isEmpty() const (this=0x18) at ../../../../modules/juce_core/text/juce_String.h:296
  #2  0x0000555555989d92 in juce::XmlElement::isTextElement() const (this=0x0)
      at ../../../../modules/juce_core/xml/juce_XmlElement.cpp:840    
  #3  0x00005555559fac4b in juce::ValueTree::fromXml(juce::XmlElement const&) (xml=...)
      at ../../../../modules/juce_data_structures/values/juce_ValueTree.cpp:1002
  #4  0x0000555555657a19 in (anonymous namespace)::setGlobalPath(juce::ArgumentList const&) (args=...)
      at ../../Source/Application/jucer_CommandLine.cpp:715
  #5  0x0000555555659bfc in <lambda()>::operator()(void) const (__closure=0x7fffffffdcf0)
      at ../../Source/Application/jucer_CommandLine.cpp:912
  #6  0x000055555565a26b in std::_Function_handler<int(), performCommandLine(const juce::ArgumentList&)::<lambda()> >::_M_invo
  #7  0x00005555559cd468 in std::function<int ()>::operator()() const (this=0x7fffffffdcf0)
      at /usr/include/c++/8/bits/std_function.h:687
  #8  0x0000555555969aba in juce::ConsoleApplication::invokeCatchingFailures(std::function<int ()>&&) (f=...)
      at ../../../../modules/juce_core/misc/juce_ConsoleApplication.cpp:201
  #9  0x0000555555659d6d in performCommandLine(juce::ArgumentList const&) (args=...)
      at ../../Source/Application/jucer_CommandLine.cpp:881
  #10 0x000055555566b884 in ProjucerApplication::initialise(juce::String const&) (this=0x5555560d9b50, commandLine=...)
      at ../../Source/Application/jucer_Application.cpp:94
  #11 0x0000555555a0b7ac in juce::JUCEApplicationBase::initialiseApp() (this=0x5555560d9b50)
      at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:297
  #12 0x0000555555b80740 in juce::JUCEApplication::initialiseApp() (this=0x5555560d9b50)
      at ../../../../modules/juce_gui_basics/application/juce_Application.cpp:93
  #13 0x0000555555a0b664 in juce::JUCEApplicationBase::main() ()
      at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:256
  #14 0x0000555555a0b576 in juce::JUCEApplicationBase::main(int, char const**) (argc=5, argv=0x7fffffffdfe8)
      at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:240
  #15 0x00005555556756d1 in main(int, char**) (argc=5, argv=0x7fffffffdfe8) at ../../Source/Application/jucer_Main.cpp:70
  (gdb) 
~~~

**Comment by ed95** [comment]
Thanks for the report, fixed in [6a3825f](https://github.com/WeAreROLI/JUCE/commit/6a3825f88f478ac91d9ec2339bf26a157a95b737).
