### ISSUE TITLE
Android crashes when back key is hit.

### ISSUE THREAD

**Issue by audiooffler** [WeAreROLI/JUCE#492]
1) Building and executing an **Android app**, e.g. the Juce DemoRunner, based on the current JUCE version, 5.4.3 (or develop 77db5fde66d0946103f544e17ebbcc748bf6fb56), will **crash when using the back button/key** of the android system. An error happens at com.roli.juce.ComponentPeerView.onKeyDown(ComponentPeerView.java:243): com.roli.juce.JuceApp cannot be cast to android.app.Activity

2) Expected: back button/key of android system should be either ignored or handled by JUCE / the app correctly.

3) Android
4) armeabi-v7a

5) Logcat output:
```
2019-02-27 17:05:32.845 8730-8730/com.juce.demorunner E/InputEventSender: Exception dispatching finished signal.
2019-02-27 17:05:32.845 8730-8730/com.juce.demorunner E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2019-02-27 17:05:32.847 8730-8730/com.juce.demorunner E/MessageQueue-JNI: java.lang.ClassCastException: com.roli.juce.JuceApp cannot be cast to android.app.Activity
        at com.roli.juce.ComponentPeerView.onKeyDown(ComponentPeerView.java:243)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2742)
        at android.view.View.dispatchKeyEvent(View.java:9950)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1662)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4751)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4722)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4404)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4285)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4461)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4285)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4437)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4598)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2512)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2106)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2097)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2487)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:356)
        at android.os.Looper.loop(Looper.java:138)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
    
    
    --------- beginning of crash
2019-02-27 17:05:32.849 8730-8730/com.juce.demorunner E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.juce.demorunner, PID: 8730
    java.lang.ClassCastException: com.roli.juce.JuceApp cannot be cast to android.app.Activity
        at com.roli.juce.ComponentPeerView.onKeyDown(ComponentPeerView.java:243)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2742)
        at android.view.View.dispatchKeyEvent(View.java:9950)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1662)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4751)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4722)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4404)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4285)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4461)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4285)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4437)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4598)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2512)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2106)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2097)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2487)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:356)
        at android.os.Looper.loop(Looper.java:138)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by ed95** [comment]
Fixed in [6eab395](https://github.com/WeAreROLI/JUCE/commit/6eab395204353d087a2ba4404dfbfa0f270aa319). Thanks for reporting.
