### ISSUE TITLE
Segfault in AudioPluginHost on Linux since https://github.com/WeAreROLI/JUCE/commit/a4bd6cbc66d8ccf58d91ed7abba243458e398d9b

### ISSUE THREAD

**Issue by KottV** [WeAreROLI/JUCE#539]
Please include:

  1) Build recent AudioPluginHost, runit, program crashes
  2) should run
  3) openSUSE TW, gcc 9.1.1
  4) 64-bit
  Backtrace:

 ```

 Program received signal SIGSEGV, Segmentation fault.
0x00000000007e4f37 in juce::LinuxComponentPeer::isMinimised (this=0xb3a570) at ../../../../modules/juce_gui_basics/native/juce_linux_X11_Windowing.cpp:1303
1303            memcpy (&state, prop.data, sizeof (unsigned long));
(gdb) bt
#0  0x00000000007e4f37 in juce::LinuxComponentPeer::isMinimised (this=0xb3a570) at ../../../../modules/juce_gui_basics/native/juce_linux_X11_Windowing.cpp:1303
#1  0x0000000000789770 in juce::ComponentPeer::handleMovedOrResized (this=0xb3a570) at ../../../../modules/juce_gui_basics/windows/juce_ComponentPeer.cpp:299
#2  0x00000000007e4c01 in juce::LinuxComponentPeer::setBounds (this=0xb3a570, newBounds=..., isNowFullScreen=false) at ../../../../modules/juce_gui_basics/native/juce_linux_X11_Windowing.cpp:1243
#3  0x0000000000788b50 in juce::ComponentPeer::updateBounds (this=0xb3a570) at ../../../../modules/juce_gui_basics/windows/juce_ComponentPeer.cpp:75
#4  0x0000000000704a98 in juce::Component::addToDesktop (this=0xb4f0e0, styleWanted=257, nativeWindowToAttachTo=0x0) at ../../../../modules/juce_gui_basics/components/juce_Component.cpp:661
#5  0x000000000078fa32 in juce::TopLevelWindow::TopLevelWindow (this=0xb4f0e0, name=..., shouldAddToDesktop=true) at ../../../../modules/juce_gui_basics/windows/juce_TopLevelWindow.cpp:141
#6  0x000000000078c3d2 in juce::ResizableWindow::ResizableWindow (this=0xb4f0e0, name=..., bkgnd=..., shouldAddToDesktop=true) at ../../../../modules/juce_gui_basics/windows/juce_ResizableWindow.cpp:37
#7  0x000000000078ad2e in juce::DocumentWindow::DocumentWindow (this=0xb4f0e0, title=..., backgroundColour=..., requiredButtons_=7, addToDesktop_=true) at ../../../../modules/juce_gui_basics/windows/juce_DocumentWindow.cpp:58
#8  0x00000000004310c5 in MainHostWindow::MainHostWindow (this=0xb4f0e0) at ../../Source/UI/MainHostWindow.cpp:79
#9  0x00000000004389ff in PluginHostApp::initialise (this=0xb37e80) at ../../Source/HostStartup.cpp:55
#10 0x0000000000619466 in juce::JUCEApplicationBase::initialiseApp (this=0xb37e80) at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:297
#11 0x00000000007937dc in juce::JUCEApplication::initialiseApp (this=0xb37e80) at ../../../../modules/juce_gui_basics/application/juce_Application.cpp:93
#12 0x0000000000619321 in juce::JUCEApplicationBase::main () at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:256
#13 0x0000000000619262 in juce::JUCEApplicationBase::main (argc=1, argv=0x7fffffffd9b8) at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:240
#14 0x0000000000438733 in main (argc=1, argv=0x7fffffffd9b8) at ../../Source/HostStartup.cpp:154

```

I reverted this commit back to fix subj:

```
@@ -2754,7 +2757,10 @@ class LinuxComponentPeer  : public ComponentPeer
     long getUserTime() const
     {
         GetXProperty prop (display, windowH, atoms->userTime, 0, 65536, false, XA_CARDINAL);
-        return prop.success ? *(long*) prop.data : 0;
+        long result;
+        memcpy (&result, prop.data, sizeof (long));
+
+        return prop.success ? result : 0;
     }
```

**Comment by ed95** [comment]
Fixed in [1ea463f](https://github.com/WeAreROLI/JUCE/commit/1ea463f9891bc5c7fc2f6a5d7f586ce1de9c2edd). Thanks for reporting!
