### ISSUE TITLE
Crashes on scanning VST (Linux)

### ISSUE THREAD

**Issue by KottV** [WeAreROLI/JUCE#647]
Please include:

  1) Run AudioPluginHost, aim to VST dir and start scanning.
  2) Plugins should be scanned and added. But crashes: JUCE Assertion failure in juce_VSTPluginFormat.cpp:2184
  3) openSUSE Tumbleweed
  4) x86_64
  5) backtrace:

```
> (gdb) bt
#0  0x00007ffff764e3b7 in kill () from /lib64/libc.so.6
#1  0x0000000000501395 in juce::VSTPluginInstance::constructEffect (module=...) at ../../../../modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp:2184
#2  0x00000000004fd55b in juce::VSTPluginInstance::create (newModule=..., initialSampleRate=48000, initialBlockSize=512) at ../../../../modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp:1165
#3  0x00000000004e0edd in juce::VSTPluginFormat::createPluginInstance(juce::PluginDescription const&, double, int, std::function<void (std::unique_ptr<juce::AudioPluginInstance, std::default_delete<juce::AudioPluginInstance> >, juce::String const&)>) (this=0xb68fb0, desc=...,sampleRate=48000, blockSize=512, callback=...) at ../../../../modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp:3604
#4  0x00000000004d2c38 in juce::AudioPluginFormat::createInstanceFromDescription (this=0xb68fb0, desc=..., initialSampleRate=48000, initialBufferSize=512, errorMessage=...) at ../../../../modules/juce_audio_processors/format/juce_AudioPluginFormat.cpp:66
#5  0x00000000004d319f in juce::AudioPluginFormatManager::createPluginInstance (this=0xb54388, description=..., rate=48000, blockSize=512, errorMessage=...) at ../../../../modules/juce_audio_processors/format/juce_AudioPluginFormatManager.cpp:97
#6  0x000000000041c528 in PluginGraph::createNodeFromXml (this=0xb64d60, xml=...) at ../../Source/Plugins/PluginGraph.cpp:386
#7  0x000000000041d325 in PluginGraph::restoreFromXml (this=0xb64d60, xml=...) at ../../Source/Plugins/PluginGraph.cpp:463
#8  0x000000000041b3c8 in PluginGraph::loadDocument (this=0xb64d60, file=...) at ../../Source/Plugins/PluginGraph.cpp:217
#9  0x000000000087d226 in juce::FileBasedDocument::loadFrom (this=0xb64d60, newFile=..., showMessageOnFailure=true) at ../../../../modules/juce_gui_extra/documents/juce_FileBasedDocument.cpp:84
#10 0x000000000043c126 in PluginHostApp::handleAsyncUpdate (this=0xb532e0) at ../../Source/HostStartup.cpp:102
#11 0x000000000062c6df in juce::AsyncUpdater::AsyncUpdaterMessage::messageCallback (this=0xb533a0) at ../../../../modules/juce_events/broadcasters/juce_AsyncUpdater.cpp:34
#12 0x000000000062e727 in juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}::operator()(int) const (__closure=0xb53128, fd=4) at ../../../../modules/juce_events/native/juce_linux_Messaging.cpp:43
#13 0x00000000006363c9 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) (__functor=..., __args#0=@0x7fffffffd874: 4) at /usr/include/c++/9/bits/std_function.h:300
#14 0x0000000000632fb2 in std::function<void (int)>::operator()(int) const (this=0xb53128, __args#0=4) at /usr/include/c++/9/bits/std_function.h:690
#15 0x000000000062f046 in juce::InternalRunLoop::dispatchPendingEvents (this=0xb530c0) at ../../../../modules/juce_events/native/juce_linux_Messaging.cpp:169
#16 0x000000000062a6b1 in juce::MessageManager::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=false) at ../../../../modules/juce_events/native/juce_linux_Messaging.cpp:260
#17 0x0000000000625683 in juce::MessageManager::runDispatchLoop (this=0xb53050) at ../../../../modules/juce_events/messages/juce_MessageManager.cpp:128
#18 0x0000000000624c0b in juce::JUCEApplicationBase::main () at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:262
#19 0x0000000000624b20 in juce::JUCEApplicationBase::main (argc=1, argv=0x7fffffffdac8) at ../../../../modules/juce_events/messages/juce_ApplicationBase.cpp:240
#20 0x000000000043b261 in main (argc=1, argv=0x7fffffffdac8) at ../../Source/HostStartup.cpp:156

```

  6) the plugin format (VST2)
  7) extras/AudioPluginHost 5.4.5-124-gc8fffa904

**Comment by KottV** [comment]
I'm closing it because it's not clear were is problem actually.
Some hosts crashes on plugins which compiled with recent JUCE, but I need to investigate more thoroughly.
